//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSDiaDiem
    {
        public int MaDS { get; set; }
        public Nullable<int> MaDD { get; set; }
        public Nullable<int> MaTour { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
