//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSPhuongTien
    {
        public int MaDSPT { get; set; }
        public Nullable<int> MaPT { get; set; }
        public Nullable<int> MaDoan { get; set; }
    
        public virtual DoanDuLich DoanDuLich { get; set; }
        public virtual PhuongTien PhuongTien { get; set; }
    }
}
