//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan
    {
        public int MaKS { get; set; }
        public string TenKS { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<int> ChiPhi { get; set; }
        public Nullable<int> MaKhuVuc { get; set; }
    }
}
