//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachDuLich
    {
        public int MaKhachDL { get; set; }
        public Nullable<int> MaDoan { get; set; }
        public Nullable<int> MaKH { get; set; }
    }
}
