//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public Nullable<int> Avatar { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string CMND { get; set; }
        public string SDT { get; set; }
        public string Taikhoan { get; set; }
        public string Password { get; set; }
        public Nullable<int> MaLoaiUser { get; set; }
    }
}
